"""Pull titles and abstracts from each paper's titleInput.tex into the CV."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
MANIFEST = ROOT / "papers.json"
OUT_DIR = ROOT / "generated"
OUT_FILE = OUT_DIR / "research_in_progress.tex"


def find_braced_arg(text: str, open_brace: int) -> tuple[str, int]:
    if text[open_brace] != "{":
        raise ValueError("expected '{'")
    depth = 0
    i = open_brace
    while i < len(text):
        ch = text[i]
        if ch == "\\" and i + 1 < len(text) and text[i + 1] in "{}\\":
            i += 2
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[open_brace + 1 : i], i + 1
        i += 1
    raise ValueError("unbalanced braces")


def strip_command(text: str, name: str) -> str:
    pattern = re.compile(r"\\" + name + r"\s*\{")
    while True:
        match = pattern.search(text)
        if not match:
            return text
        _, end = find_braced_arg(text, match.end() - 1)
        text = text[: match.start()] + text[end:]


def strip_line_comments(text: str) -> str:
    lines = []
    for line in text.splitlines():
        out = []
        i = 0
        while i < len(line):
            if line[i] == "\\" and i + 1 < len(line):
                out.append(line[i : i + 2])
                i += 2
                continue
            if line[i] == "%":
                break
            out.append(line[i])
            i += 1
        lines.append("".join(out))
    return "\n".join(lines)


def collapse_ws(text: str) -> str:
    text = text.replace("\n", " ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def extract_title(tex: str) -> str:
    match = re.search(r"\\title\s*\{", tex)
    if match:
        raw, _ = find_braced_arg(tex, match.end() - 1)
        raw = strip_command(raw, "thanks")
        raw = strip_line_comments(raw)
        raw = re.sub(r"\\(?:Large|large|bfseries|textbf)\s*", "", raw)
        raw = re.sub(r"\\\\(?:\[[^\]]*\])?", " ", raw)
        title = collapse_ws(raw).strip(" {}")
        if title:
            return title

    bf = re.search(r"\\bfseries\s*([^}\\]+)", tex)
    small = re.search(r"\{\\small\s+([^}]+)\}", tex)
    if bf:
        main = collapse_ws(bf.group(1))
        if small:
            sub = collapse_ws(strip_line_comments(small.group(1)))
            return f"{main}: {sub}"
        return main

    raise ValueError("could not find a title")


def extract_abstract(tex: str) -> str:
    match = re.search(r"\\begin\{abstract\}(.*)\\end\{abstract\}", tex, re.S)
    if not match:
        raise ValueError("could not find abstract")
    body = strip_line_comments(match.group(1))
    kept = []
    for line in body.splitlines():
        if re.search(r"(?i)\\textbf\{Keywords\}|Keywords:|\\textbf\{JEL|JEL Codes:|JEL:", line):
            continue
        kept.append(line)
    body = "\n".join(kept)
    body = re.sub(r"\\noindent\s*", "", body)
    body = re.sub(r"\\footnotesize\s*", "", body)
    body = re.sub(r"\\enspace\s*", " ", body)
    body = re.sub(r"\\bigskip\s*", "", body)
    body = re.sub(r"\\vspace\*?\{[^}]*\}\s*", "", body)
    body = re.sub(r"\\setlength\{[^}]*\}\{[^}]*\}\s*", "", body)
    body = re.sub(r"\\\\(?:\[[^\]]*\])?", " ", body)
    return collapse_ws(body)


def heading(title: str, job_market: bool, with_authors: str | None) -> str:
    pieces = [title]
    if job_market:
        pieces[0] = f"{title} (Job Market Paper)"
    head = f"\\textbf{{{pieces[0]}}}"
    if with_authors:
        head += f", with {with_authors}."
    return head + "\\\\[0.35em]"


def render(papers: list[dict]) -> str:
    blocks = ["% Auto-generated by extract_papers.py. Edit papers.json or the paper titleInput.tex files.", "\\section*{Research in Progress}"]
    for i, paper in enumerate(papers):
        src = Path(paper["source"])
        if not src.is_file():
            raise FileNotFoundError(f"paper source not found: {src}")
        tex = strip_line_comments(src.read_text(encoding="utf-8"))
        title = extract_title(tex)
        abstract = extract_abstract(tex)
        if not abstract:
            raise ValueError(f"empty abstract in {src}")
        block = [heading(title, bool(paper.get("job_market_paper")), paper.get("with")), abstract + "\\par"]
        presentation = paper.get("presentation")
        if presentation:
            block.append("\\vspace*{0.05in}")
            block.append(f"\\textit{{Presentation}}: {presentation}\\par")
        blocks.append("\n".join(block))
        if i != len(papers) - 1:
            blocks.append("\\vspace*{0.12in}")
    return "\n".join(blocks) + "\n"


def main() -> int:
    spec = json.loads(MANIFEST.read_text(encoding="utf-8"))
    papers = spec["papers"]
    for paper in papers:
        paper["source"] = str((ROOT / paper["source"]).resolve())
    tex = render(papers)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(tex, encoding="utf-8")
    print(f"Wrote {OUT_FILE}")
    for paper in papers:
        src = Path(paper["source"])
        title = extract_title(strip_line_comments(src.read_text(encoding="utf-8")))
        print(f"  - {title}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"extract_papers.py: {exc}", file=sys.stderr)
        raise SystemExit(1)
